import Head from 'next/head'
import Header from '../components/header/Header'

import { useState } from 'react';
import Navbar from '../components/navbar/Navbar';

export default function Home() {

  const [isSearchOpen, setIsSearchOpen] = useState(false);

  return (
    <div className='bg-[#fcfcfc] min-h-[2000px] ' >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header isSearchOpen={isSearchOpen} setIsSearchOpen={setIsSearchOpen} />

      <Navbar />

      <div className={` ${isSearchOpen ? "block" : "hidden"} block fixed top-0 bottom-0 right-0 w-full h-full bg-[#acacac] opacity-50  z-[49]   `} />





    </div>
  )
}
