export const ALL_CATEGORY_SUCCESS = 'ALL_CATEGORY_SUCCESS'
export const ALL_CATEGORY_FAIL = 'ALL_CATEGORY_FAIL'

export const SET_CATEGORY_SUCCESS = "SET_CATEGORY_SUCCESS"
export const SET_CATEGORY_FAIL = "SET_CATEGORY_FAIL"

export const SET_SHEARCHITEMS_SUCCESS = "SET_SHEARCHITEMS_SUCCESS"
export const RESET_SHEARCHITEMS = "RESET_SHEARCHITEMS"
export const RESET_SHEARCHPARAMS = "RESET_SHEARCHPARAMS"


export const UPDATE_SHEARCHPARAMS = "UPDATE_SHEARCHPARAMS"
export const UPDATE_SHEARCHPARAMS_DYNAMICNAME = "UPDATE_SHEARCHPARAMS_DYNAMICNAME"
export const UPDATE_SHEARCHPARAMS_DYNAMICVALUE = "UPDATE_SHEARCHPARAMS_DYNAMICVALUE"

export const ALL_ADVERTISES_REQUEST = 'ALL_ADVERTISES_REQUEST'
export const ALL_ADVERTISES_SUCCESS = 'ALL_ADVERTISES_SUCCESS'
export const UPDATE_ADVERTISES_SUCCESS = 'UPDATE_ADVERTISES_SUCCESS'
export const ALL_ADVERTISES_FAIL = 'ALL_ADVERTISES_FAIL'
export const EMPTY_ADVERTISES = 'EMPTY_ADVERTISES'


export const UPDATE_PAGE = 'UPDATE_PAGE'












