
export const REQUEST_LOADING = "REQUEST_LOADING"
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS"
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL"

export const USER_LOGOUT_FAIL = "USER_LOGOUT_FAIL"
export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS"

export const CLEAR_ERROR = "CLEAR_ERROR"




